# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Hello\ world.o"
LINKOBJ  = "Hello world.o"
LIBS     = -L"F:/python programs/Dev-Cpp/MinGW64/lib" -L"F:/python programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/python programs/Dev-Cpp/MinGW64/include" -I"F:/python programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/python programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/python programs/Dev-Cpp/MinGW64/include" -I"F:/python programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/python programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/python programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"Hello\ world.o": Hello\ world.cpp
	$(CPP) -c "Hello world.cpp" -o "Hello world.o" $(CXXFLAGS)
